buildoptions = {
						---------------------
						-- GALACTIC EMPIRE --
						---------------------
			--each commander variant needs the buildmenu copypasted
	imp_commander = {
		"imp_c_protocon",
		"imp_sc_probedroid",
		"imp_i_scouttrooper",
		"imp_sc_speederbike",
	},
	imp_com_mil1 = {
		"imp_c_protocon",
		"imp_sc_probedroid",
		"imp_i_eweb",
		"imp_i_rockettrooper",
		"imp_i_scouttrooper",
		"imp_sc_speederbike",
	},
	imp_com_res1 = {
		"imp_c_protocon",
		"imp_sc_probedroid",
		"imp_i_stormtrooper",
		"imp_i_flametrooper",
		"imp_i_reptrooper",
		"imp_i_scouttrooper",
		"imp_sc_speederbike",
	},
	imp_com_mil2 = {
		"imp_c_protocon",
		"imp_sc_probedroid",
		"imp_i_royalguard",
		"imp_i_eweb",
		"imp_i_rockettrooper",
		"imp_i_scouttrooper",
		"imp_sc_speederbike",
	},
	imp_com_res2 = {
		"imp_c_protocon",
		"imp_sc_probedroid",
		"imp_i_darktrooper",
		"imp_i_stormtrooper",
		"imp_i_flametrooper",
		"imp_i_reptrooper",
		"imp_i_scouttrooper",
		"imp_sc_speederbike",
	},
	imp_c_protocon = {
		"imp_p_solar",
		"imp_p_estore",
		"imp_sp_sensor",
		"imp_b_barracks",
		"imp_b_droidplant",
		"imp_d_pillbox",
		"imp_d_fence",
	},
	imp_c_condroid = {
		"imp_p_fusion",
		"imp_p_solar",
		"imp_p_estore",
		"imp_p_tibanna",
		"imp_b_barracks",
		"imp_b_droidplant",
		"imp_b_airplant",
		"imp_b_airplantadv",
		"imp_b_vehicleplant",
		"imp_b_walkerplant",
		"imp_sp_sensor",
		"imp_d_pillbox",
		"imp_d_ioncannon",
		"imp_d_turbolaser",
		"imp_d_antiair",
		"imp_d_fence",
	},
	imp_c_walker = {
		"imp_p_fusionadv",
		"imp_d_turbolaser",
		"imp_d_artillery",
		"imp_d_antiairadv",
	},
	imp_b_barracks = {
		"imp_c_condroid",
		"imp_is_scout",
		"imp_is_assault",
		"imp_is_heavy",
		"imp_is_defense",
		"imp_is_antiair",
		"imp_w_atrt",
		"imp_v_groundtransport",
	},
	imp_b_droidplant = {
		"imp_c_condroid",
		"imp_sc_stap",
		"imp_i_droideka",
		"imp_is_b1",
		"imp_i_superbattledroid",
		"imp_w_crabdroid",
		"imp_v_hailfire",
	},
	imp_b_vehicleplant = {
		"imp_c_condroid",
		"imp_v_tiecrawler",
		"imp_a_cloudcar",
		"imp_v_mobileartillery",
		"imp_v_tx130",
	},
	imp_b_walkerplant = {
		"imp_c_walker",
		"imp_w_atar",
		"imp_w_atxt",
		"imp_w_ataa",
		"imp_w_atmd",
		"imp_w_atst",
		"imp_w_atstas",
	},
	imp_b_airplant = {
		"imp_a_tiedroid",
		"imp_a_tiefighter",
		"imp_a_tieinterceptor",
		"imp_a_tiebomber",
		"imp_a_laat",
		"imp_a_laatc",
	},
	imp_b_airplantadv = {
		"imp_a_tiephantom",
		"imp_a_tiedefender",
		"imp_a_scimitar",
		"imp_a_gunboat",
	},
						---------------------
						-- REBEL ALLIANCE  --
						---------------------
			--each commander variant needs the buildmenu copypasted
	reb_commander = {
		"reb_b_barracks",
		"reb_p_varenergy",
		"reb_p_estore",
		"reb_sp_sensor",
		"reb_p_fusion",
		"reb_sp_spotter",
		"reb_d_fence",
	},
	reb_com_armor1 = {
		"reb_b_barracks",
		"reb_p_varenergy",
		"reb_p_estore",
		"reb_sp_sensor",
		"reb_p_fusion",
		"reb_sp_spotter",
		"reb_d_fence",
	},
	reb_com_builder1 = {
		"reb_b_barracks",
		"reb_p_varenergy",
		"reb_p_estore",
		"reb_p_tibanna",
		"reb_p_fusion",
		"reb_b_airplant",
		"reb_b_repulsorliftplant",
		"reb_b_heavyweaponslab",
		"reb_sp_sensor",
		"reb_sp_spotter",
		"reb_d_golan",
		"reb_d_atgar",
		"reb_d_antiair",
		"reb_d_fence",
	},
	reb_i_bothan = {
		"reb_is_balanced",
		"reb_is_sniper",
		"reb_is_heavy",
	},
	reb_c_condroid = {
		"reb_p_fusion",
		"reb_p_varenergy",
		"reb_p_estore",
		"reb_p_tibanna",
		"reb_b_barracks",
		"reb_b_airplant",
		"reb_b_repulsorliftplant",
		"reb_b_heavyweaponslab",
		"reb_sp_sensor",
		"reb_sp_spotter",
		"reb_d_golan",
		"reb_d_atgar",
		"reb_d_antiair",
		"reb_d_fence",
	},
	reb_p_flagmil1 = {
		"reb_i_trooper",
		"reb_i_combat",
		"reb_i_wookiee",
	},
	reb_b_barracks = {
		"reb_c_condroid",
		"reb_v_landspeeder",
		"reb_sc_swoop",
		"reb_i_trooper",
		"reb_i_combat",
		"reb_i_wookiee",
		"reb_i_bothan",
		"reb_i_mrb",
		"reb_i_rockettrooper",
		"reb_w_espo",
		"reb_a_shuttle",
	},
	reb_b_repulsorliftplant = {
		"reb_c_condroid",
		"reb_v_ulav",
		"reb_a_airspeeder",
		"reb_v_t1b",
		"reb_v_t2b",
		"reb_a_vwing",
		"reb_v_groundtransport",
	},
	reb_b_heavyweaponslab = {
		"reb_com_builder2",
		"reb_w_atpt",
		"reb_v_stormcannon",
		"reb_v_t4c",
		"reb_v_heavytracker",
		"reb_v_mptl",
	},
	reb_b_airplant = {
		"reb_a_twing",
		"reb_a_z95",
		"reb_a_awing",
		"reb_a_ywing",
		"reb_a_transport",
		"reb_a_shuttle",
	},
	reb_b_airplantadv = {
		"reb_a_bwing",
		"reb_a_ewing",
		"reb_a_xwing",
	},
}

return buildoptions